[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# --- ADD THIS BLOCK ---
# Increase the timeout for the processMint function specifically
[functions."processMint"]
  timeout = 30 # Timeout in seconds

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200