[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."processMint.mjs"]
  timeout = 120

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200