[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# --- ADD THIS BLOCK ---
# Increase the timeout for the processMint function specifically
[functions."processMint.js"] # Make sure the name matches your file name
  timeout = 120 # Timeout in seconds

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200