[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# This block is for .js files and applies the timeout
[functions."processMint.js"]
  timeout = 120 # Timeout in seconds

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200